-- Add down migration script here
DROP TABLE IF EXISTS users CASCADE;
DROP TABLE IF EXISTS data;
DROP TABLE IF EXISTS instagram;
DROP TABLE IF EXISTS facebook;
DROP TABLE IF EXISTS github;
DROP TABLE IF EXISTS contact;