-- Add up migration script here
CREATE TABLE IF NOT EXISTS users (
    id INT PRIMARY KEY GENERATED ALWAYS AS IDENTITY,
    created_at TIMESTAMP NOT NULL DEFAULT NOW(),
    name VARCHAR NOT NULL
);
CREATE TABLE IF NOT EXISTS instagram(
    id INT PRIMARY KEY GENERATED ALWAYS AS IDENTITY,
    created_at TIMESTAMP NOT NULL DEFAULT NOW(),
    link VARCHAR NOT NULL
);
CREATE TABLE IF NOT EXISTS facebook(
    id INT PRIMARY KEY GENERATED ALWAYS AS IDENTITY,
    created_at TIMESTAMP NOT NULL DEFAULT NOW(),
    link VARCHAR NOT NULL
);
CREATE TABLE IF NOT EXISTS github(
    id INT PRIMARY KEY GENERATED ALWAYS AS IDENTITY,
    created_at TIMESTAMP NOT NULL DEFAULT NOW(),
    link VARCHAR NOT NULL
);
CREATE TABLE IF NOT EXISTS contact(
    id INT PRIMARY KEY GENERATED ALWAYS AS IDENTITY,
    created_at TIMESTAMP NOT NULL DEFAULT NOW(),
    mobile_number INT,
    address VARCHAR
);
CREATE TABLE IF NOT EXISTS data(
    id INT PRIMARY KEY GENERATED ALWAYS AS IDENTITY,
    created_at TIMESTAMP NOT NULL DEFAULT NOW(),
    user_id INT NOT NULL,
    instagram_id INT,
    facebook_id INT,
    github_id INT,
    contact_id INT,
    FOREIGN KEY (user_id) REFERENCES users,
    FOREIGN KEY (instagram_id) REFERENCES instagram,
    FOREIGN KEY (facebook_id) REFERENCES facebook,
    FOREIGN KEY (github_id) REFERENCES github,
    FOREIGN KEY (contact_id) REFERENCES contact
);