-- Add up migration script here
CREATE TABLE IF NOT EXISTS users (
    id INTEGER PRIMARY KEY GENERATED ALWAYS AS IDENTITY,
    created_at TIMESTAMP NOT NULL DEFAULT NOW(),
    name VARCHAR UNIQUE NOT NULL
);
CREATE TABLE IF NOT EXISTS instagram(
    id INTEGER PRIMARY KEY GENERATED ALWAYS AS IDENTITY,
    created_at TIMESTAMP NOT NULL DEFAULT NOW(),
    link VARCHAR
);
CREATE TABLE IF NOT EXISTS facebook(
    id INTEGER PRIMARY KEY GENERATED ALWAYS AS IDENTITY,
    created_at TIMESTAMP NOT NULL DEFAULT NOW(),
    link VARCHAR
);
CREATE TABLE IF NOT EXISTS github(
    id INTEGER PRIMARY KEY GENERATED ALWAYS AS IDENTITY,
    created_at TIMESTAMP NOT NULL DEFAULT NOW(),
    link VARCHAR
);
CREATE TABLE IF NOT EXISTS contact(
    id INTEGER PRIMARY KEY GENERATED ALWAYS AS IDENTITY,
    created_at TIMESTAMP NOT NULL DEFAULT NOW(),
    mobile_number VARCHAR,
    address VARCHAR
);
CREATE TABLE IF NOT EXISTS data(
    id INTEGER PRIMARY KEY GENERATED ALWAYS AS IDENTITY,
    created_at TIMESTAMP NOT NULL DEFAULT NOW(),
    user_id INTEGER,
    instagram_id INTEGER,
    facebook_id INTEGER,
    github_id INTEGER,
    contact_id INTEGER,
    FOREIGN KEY (user_id) REFERENCES users,
    FOREIGN KEY (instagram_id) REFERENCES instagram,
    FOREIGN KEY (facebook_id) REFERENCES facebook,
    FOREIGN KEY (github_id) REFERENCES github,
    FOREIGN KEY (contact_id) REFERENCES contact
);